# Generated by Django 5.1.4 on 2024-12-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers_alter_customuser_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                ("visited", models.BooleanField(default=False)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_places",
                        to="users.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
