# Generated by Django 5.1.4 on 2024-12-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_place_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
