# Generated by Django 5.1.4 on 2024-12-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_trip_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://www.travelturtle.world/wp-content/uploads/2024/03/6585d85934a171a9a052c170_traveling-based-on-fare-deals.jpeg",
                null=True,
            ),
        ),
    ]
